# Generated by Django 5.2.17 on 2026-08-07 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0002_remove_university_campus_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSource',
            fields=[
                ('source_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admission_year', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('ADIGA', '대입정보포털 어디가'), ('UNIVERSITY', '대학 입학처'), ('OTHER', '기타')], max_length=20)),
                ('source_url', models.URLField(max_length=1000)),
                ('document_title', models.CharField(blank=True, max_length=300)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sources', to='universities.university')),
            ],
            options={
                'db_table': 'admission_sources',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentUnit',
            fields=[
                ('recruitment_unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('college_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_units', to='universities.universitycampus')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_units', to='universities.university')),
            ],
            options={
                'db_table': 'recruitment_units',
            },
        ),
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admission_year', models.PositiveIntegerField()),
                ('admission_phase', models.CharField(choices=[('SUSI', '수시'), ('JEONGSI', '정시')], max_length=10)),
                ('selection_category', models.CharField(blank=True, max_length=100)),
                ('selection_name', models.CharField(blank=True, max_length=200)),
                ('recruitment_group', models.CharField(blank=True, max_length=30)),
                ('recruitment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('applicant_count', models.PositiveIntegerField(blank=True, null=True)),
                ('registered_count', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_results', to='universities.university')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='admissions.admissionsource')),
                ('recruitment_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_results', to='admissions.recruitmentunit')),
            ],
            options={
                'db_table': 'admission_results',
            },
        ),
        migrations.CreateModel(
            name='AdmissionAggregate',
            fields=[
                ('aggregate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admission_year', models.PositiveIntegerField()),
                ('admission_phase', models.CharField(choices=[('SUSI', '수시'), ('JEONGSI', '정시')], max_length=10)),
                ('selection_category', models.CharField(blank=True, max_length=100)),
                ('metric_code', models.CharField(max_length=100)),
                ('aggregation_method', models.CharField(choices=[('SIMPLE_AVERAGE', '단순 평균'), ('WEIGHTED_BY_RECRUITMENT', '모집인원 가중평균')], max_length=30)),
                ('value', models.DecimalField(decimal_places=5, max_digits=14)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_aggregates', to='universities.university')),
            ],
            options={
                'db_table': 'admission_aggregates',
                'constraints': [models.UniqueConstraint(fields=('university', 'admission_year', 'admission_phase', 'selection_category', 'metric_code', 'aggregation_method'), name='uq_admission_aggregate')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionMetric',
            fields=[
                ('metric_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_code', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=5, max_digits=14)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='admissions.admissionresult')),
            ],
            options={
                'db_table': 'admission_metrics',
                'indexes': [models.Index(fields=['metric_code'], name='admission_m_metric__ee0bdd_idx')],
                'constraints': [models.UniqueConstraint(fields=('result', 'metric_code'), name='uq_result_metric_code')],
            },
        ),
        migrations.AddIndex(
            model_name='admissionsource',
            index=models.Index(fields=['university', 'admission_year'], name='admission_s_univers_dbe069_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentunit',
            constraint=models.UniqueConstraint(fields=('university', 'campus', 'name'), name='uq_recruitment_unit'),
        ),
        migrations.AddIndex(
            model_name='admissionresult',
            index=models.Index(fields=['university', 'admission_year', 'admission_phase'], name='admission_r_univers_9b384d_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionresult',
            index=models.Index(fields=['selection_category'], name='admission_r_selecti_47115c_idx'),
        ),
    ]
