# Generated by Django 5.2.17 on 2026-08-07 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0002_remove_university_campus_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingBoard',
            fields=[
                ('board_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ranking_boards',
                'ordering': ['display_order', 'board_id'],
            },
        ),
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('snapshot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('total_votes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='rankings.rankingboard')),
            ],
            options={
                'db_table': 'ranking_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='RankingSnapshotItem',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('match_count', models.PositiveBigIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rankings.rankingsnapshot')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_snapshot_items', to='universities.university')),
            ],
            options={
                'db_table': 'ranking_snapshot_items',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='UniversityRating',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=1500.0)),
                ('rating_deviation', models.FloatField(default=350.0)),
                ('volatility', models.FloatField(default=0.06)),
                ('match_count', models.PositiveBigIntegerField(default=0)),
                ('win_count', models.PositiveBigIntegerField(default=0)),
                ('loss_count', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rankings.rankingboard')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='universities.university')),
            ],
            options={
                'db_table': 'university_ratings',
            },
        ),
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('vote_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunirank_vote_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vote_sessions',
            },
        ),
        migrations.CreateModel(
            name='PersonalResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('result_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_results', to='rankings.rankingboard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_results', to='rankings.votesession')),
            ],
            options={
                'db_table': 'personal_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonVote',
            fields=[
                ('vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_votes', to='universities.university')),
                ('university_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes_as_a', to='universities.university')),
                ('university_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes_as_b', to='universities.university')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='rankings.rankingboard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='rankings.votesession')),
            ],
            options={
                'db_table': 'comparison_votes',
                'ordering': ['vote_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rankingsnapshot',
            constraint=models.UniqueConstraint(fields=('board', 'snapshot_date'), name='uq_snapshot_board_date'),
        ),
        migrations.AddConstraint(
            model_name='rankingsnapshotitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'university'), name='uq_snapshot_university'),
        ),
        migrations.AddConstraint(
            model_name='rankingsnapshotitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'rank'), name='uq_snapshot_rank'),
        ),
        migrations.AddIndex(
            model_name='universityrating',
            index=models.Index(fields=['board', 'rating'], name='university__board_i_231251_idx'),
        ),
        migrations.AddIndex(
            model_name='universityrating',
            index=models.Index(fields=['board', 'match_count'], name='university__board_i_4a9bc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='universityrating',
            constraint=models.UniqueConstraint(fields=('board', 'university'), name='uq_rating_board_university'),
        ),
        migrations.AddIndex(
            model_name='votesession',
            index=models.Index(fields=['session_key', 'last_seen_at'], name='vote_sessio_session_f7db27_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonvote',
            index=models.Index(fields=['board', 'created_at'], name='comparison__board_i_629732_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonvote',
            index=models.Index(fields=['session', 'created_at'], name='comparison__session_f75026_idx'),
        ),
    ]
