# Generated by Django 5.2.17 on 2026-08-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('legacy_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('campus_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('university_type', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campuses', to='universities.university')),
            ],
            options={
                'db_table': 'universities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='universitie_name_3cb454_idx'), models.Index(fields=['region'], name='universitie_region_53ce56_idx')],
            },
        ),
    ]
