# Generated by Django 5.2.17 on 2026-08-07 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='campus_name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='university',
            name='parent_university',
        ),
        migrations.AddField(
            model_name='university',
            name='college_info_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='establishment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='homepage_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('campus_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('external_code', models.CharField(max_length=100)),
                ('campus_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='universities.university')),
            ],
            options={
                'db_table': 'university_campuses',
            },
        ),
        migrations.CreateModel(
            name='UniversityExternalMapping',
            fields=[
                ('mapping_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('external_code', models.CharField(max_length=100)),
                ('external_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_mappings', to='universities.universitycampus')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='universities.university')),
            ],
            options={
                'db_table': 'university_external_mappings',
            },
        ),
        migrations.AddIndex(
            model_name='universitycampus',
            index=models.Index(fields=['university'], name='university__univers_77f07f_idx'),
        ),
        migrations.AddConstraint(
            model_name='universitycampus',
            constraint=models.UniqueConstraint(fields=('source', 'external_code'), name='uq_campus_source_code'),
        ),
        migrations.AddIndex(
            model_name='universityexternalmapping',
            index=models.Index(fields=['source', 'external_code'], name='university__source_4d4a1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='universityexternalmapping',
            constraint=models.UniqueConstraint(fields=('source', 'external_code'), name='uq_external_source_code'),
        ),
    ]
